### ISSUE TITLE
go-delegated-routing cannot properly handle streaming responses

### ISSUE THREAD

**Issue by aschmahmann** [ipfs-shipyard/someguy#1]
go-delegated-routing is unable to process streaming responses. This is due to using the DAG-JSON decoder https://github.com/ipfs/go-delegated-routing/blob/3729ba353037ef1c0d40ba1e87b352acda9c7283/gen/proto/proto_edelweiss.go#L1188 and that decoder not allowing for streaming reads https://github.com/ipld/go-ipld-prime/issues/374.

Once this is fixed in go-delegated-routing (either via some config in go-ipld-prime, or in the code generated by edelweiss) this should be resolved.

cc @ajnavarro @petar

**Comment by petar** [comment]
This is addressed in https://github.com/ipld/go-ipld-prime/pull/435 (underway)

**Comment by petar** [comment]
This issue is now resolved by https://github.com/ipfs/go-delegated-routing/pull/26

**Comment by aschmahmann** [comment]
fixed in #2
